version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
- package-ecosystem: pip
  directory: /
  schedule:
    interval: weekly
  groups:
    production dependencies:
      dependency-type: production
    development dependencies:
      dependency-type: development
  target-branch: develop
